# .pre-commit-config.yaml
repos:
  # Universal hooks (language-agnostic)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Update to latest version
    hooks:
      - id: trailing-whitespace  # Trims trailing whitespace
      - id: end-of-file-fixer    # Ensures files end with a newline
      - id: check-yaml           # Validates YAML syntax
      - id: check-added-large-files  # Blocks large files

  # Python hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # run formatting after linting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black  # Auto-formats Python code
